# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku060-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.cache/wt [current_project]
set_property parent.project_path /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128.dcp
set_property used_in_implementation false [get_files /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128.dcp]
add_files -quiet /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/pcie3_ultrascale_0/pcie3_ultrascale_0.dcp
set_property used_in_implementation false [get_files /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/pcie3_ultrascale_0/pcie3_ultrascale_0.dcp]
read_verilog {
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/BasePicoDefines.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/PicoDefines.v
}
set_property file_type "Verilog Header" [get_files /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/BasePicoDefines.v]
set_property file_type "Verilog Header" [get_files /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/PicoDefines.v]
read_verilog -library xil_defaultlib {
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/Reorder.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/CounterClkGen.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/fifo_512x128.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/xilinx/src/FIFO.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PCIeHdrAlignSplit.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PicoStreamIn.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PicoStreamOut.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PIO_128_RX_ENGINE.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PIO_128_TX_ENGINE.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/StreamToPicoBus.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/TagFIFO.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/CardInfo32.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PIO_EP.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/Stream2PicoBus.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/SystemMonitor32.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/TestCounter32.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/xilinx/src/pcie3_7x_to_v1_6.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/pcie_app_v6.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/StreamWidthConversion.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/xilinx/src/xilinx_pcie_3_0_7vx.v
  /home/micron/StreamLoopback128/firmware/StreamLoopback128.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/PicoFramework.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/UserWrapper.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/RGBBlink.v
  /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/src/pcie_axi/Pico_Toplevel.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/m510/src/M510_KU060_FFVA1156_E.xdc
set_property used_in_implementation false [get_files /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/m510/src/M510_KU060_FFVA1156_E.xdc]

read_xdc -unmanaged /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/m510/src/clocks.tcl
set_property used_in_implementation false [get_files /home/micron/StreamLoopback128/firmware/M510_KU060_StreamLoopback128/firmware/m510/src/clocks.tcl]


synth_design -top Pico_Toplevel -part xcku060-ffva1156-2-e


write_checkpoint -force -noxdef Pico_Toplevel.dcp

catch { report_utilization -file Pico_Toplevel_utilization_synth.rpt -pb Pico_Toplevel_utilization_synth.pb }
