# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/micron/OriginalStreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128.xci
# IP: The module: 'coregen_fifo_32x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/micron/OriginalStreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128/coregen_fifo_32x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_fifo_32x128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/micron/OriginalStreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_fifo_32x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/micron/OriginalStreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128.xci
# IP: The module: 'coregen_fifo_32x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/micron/OriginalStreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128/coregen_fifo_32x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_fifo_32x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/micron/OriginalStreamLoopback128/firmware/M510_KU060_StreamLoopback128/M510_KU060_StreamLoopback128.srcs/sources_1/ip/coregen_fifo_32x128/coregen_fifo_32x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_fifo_32x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
